global:
  scrape_interval: 15s
scrape_configs:
  - job_name: api
    metrics_path: /api/metrics
    static_configs:
      - targets: ["api:8080"]
  - job_name: worker
    metrics_path: /
    static_configs:
      - targets: ["worker:9808"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
